### ISSUE TITLE
Use for Streaming Record Batches?

### ISSUE THREAD

**Issue by mindjuice** [graphistry/arrow#8]
The Table abstraction is good when you have all the data, but I want to be able to receive an initial message (over a websocket) with a schema and the first record batch, and then periodically receive more record batches for the same schema on the websocket.

Is there an easy way to bend this code to my will or is an additional abstraction required?

**Comment by trxcllnt** [comment]
@mindjuice yes! we plan to support streaming record batches via AsyncIterables (and an Observable API should follow soon after). We haven't done it yet, but we just need an async generator form of [`readBuffers`](https://github.com/graphistry/arrow/blob/master/src/reader/arrow.ts#L49) and [`readStream`](https://github.com/graphistry/arrow/blob/master/src/reader/stream.ts#L28), e.g:

```ts
export async function* readBuffersAsync(buffers: AsyncIterable<Uint8Array | Buffer | string>) {
    const dictionaries: Dictionaries = {};
    for await (let { schema, batch } of readStreamAsync(buffers)) {
        /* etc. */
        yield vectors;
    }
}
```

**Comment by mindjuice** [comment]
Cool...looking forward to that.  I think I've found a way to use the code as is for now, but that enhancement will be great.

**Comment by trxcllnt** [comment]
@mindjuice sounds good. you should be able to reuse most of the functions in `reader/` with an async scan form of `readBuffers`. If you only need access to a single RecordBatch worth of values at a time, this should be all you need. Since this is essentially what I'd do for the AsyncIterable version, feel free to submit a PR if you settle on an implementation you're happy with.

The concrete Vector types will also virtualize values across RecordBatches, so they can be accessed as a single logical Vector, so it's easy to do things like slice all values to a dense TypedArray for WebGL. The `Table.from` method [does this](https://github.com/graphistry/arrow/blob/master/src/table.ts#L29) to create a unified view of its columns across RecordBatches.
